import { MarketItem, NewsItem, CalendarEvent } from './types';

export const mockMarketData: MarketItem[] = [
  // Indici (prezzi in EUR)
  { symbol: 'SPX', name: 'S&P 500', price: 5895.00, change: -4.72, changePercent: -0.08, category: 'index' },
  { symbol: 'IXIC', name: 'NASDAQ', price: 19763.00, change: 15.81, changePercent: 0.08, category: 'index' },
  { symbol: 'FTSEMIB', name: 'FTSE MIB', price: 44085.89, change: -687.07, changePercent: -1.53, category: 'index' },
  { symbol: 'GDAXI', name: 'DAX', price: 23640.03, change: -328.45, changePercent: -1.37, category: 'index' },
  { symbol: 'N225', name: 'Nikkei 225', price: 46230.00, change: -594.09, changePercent: -1.27, category: 'index' },
  // Materie prime (prezzi in EUR)
  { symbol: 'GC=F', name: 'Oro', price: 4332.60, change: -43.67, changePercent: -1.00, category: 'commodity' },
  { symbol: 'CL=F', name: 'Petrolio WTI', price: 85.27, change: 1.12, changePercent: 1.33, category: 'commodity' },
  { symbol: 'SI=F', name: 'Argento', price: 69.17, change: -1.58, changePercent: -2.23, category: 'commodity' },
  // Crypto (prezzi in EUR da CoinGecko)
  { symbol: 'BTC', name: 'Bitcoin', price: 64100.00, change: 1500.00, changePercent: 2.40, category: 'crypto' },
  { symbol: 'ETH', name: 'Ethereum', price: 1978.00, change: 130.00, changePercent: 7.00, category: 'crypto' },
  // Valute (rapporti, non convertire)
  { symbol: 'EURUSD', name: 'EUR/USD', price: 1.1416, change: -0.0034, changePercent: -0.30, category: 'currency' },
  { symbol: 'EURGBP', name: 'EUR/GBP', price: 0.8630, change: 0.0018, changePercent: 0.21, category: 'currency' },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'La FED mantiene i tassi invariati, segnala possibili tagli nel Q3',
    description: 'Il Federal Open Market Committee ha deciso di mantenere il tasso dei fondi federali al 4.25%-4.50%, in linea con le attese del mercato. Durante la conferenza stampa, il presidente Jerome Powell ha sottolineato che l\'inflazione sta mostrando segnali di rallentamento, ma che servono ulteriori conferme prima di procedere con un taglio. Gli analisti interpretano le dichiarazioni come un segnale che i primi tagli potrebbero arrivare nel terzo trimestre del 2026, a patto che i dati sull\'occupazione e i prezzi al consumo continuino su questa traiettoria. I mercati hanno reagito positivamente, con l\'S&P 500 in rialzo dello 0.8% dopo l\'annuncio.',
    source: 'Reuters',
    url: '#',
    publishedAt: new Date().toISOString(),
    category: 'Banche Centrali',
    impact: 'high',
    imageUrl: 'https://images.unsplash.com/photo-1611324586349-d4088e31c966?w=800&h=450&fit=crop',
  },
  {
    id: '2',
    title: 'NVIDIA supera le stime: ricavi record a $39.3B nel Q4',
    description: 'NVIDIA ha riportato ricavi per $39.3 miliardi nel quarto trimestre fiscale, battendo nettamente le stime degli analisti fissate a $37.1 miliardi. La divisione data center, trainata dalla domanda esplosiva per i chip AI, ha registrato una crescita del 78% anno su anno, confermando il ruolo centrale dell\'azienda nella rivoluzione dell\'intelligenza artificiale. Il CEO Jensen Huang ha dichiarato che la domanda per le GPU Blackwell "supera ogni aspettativa" e che l\'azienda sta accelerando la produzione per far fronte agli ordini. Il titolo ha guadagnato il 4.2% nell\'after-hours, portando la capitalizzazione di mercato oltre i $3.5 trilioni.',
    source: 'Bloomberg',
    url: '#',
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    category: 'Earnings',
    impact: 'high',
    imageUrl: 'https://images.unsplash.com/photo-1640955014216-75201056c829?w=800&h=450&fit=crop',
  },
  {
    id: '3',
    title: 'UE approva nuove sanzioni contro la Russia, impatto su energia europea',
    description: 'L\'Unione Europea ha approvato all\'unanimita il quindicesimo pacchetto di sanzioni contro la Russia, con misure piu stringenti sul settore energetico e sulle esportazioni di GNL. Le nuove restrizioni colpiscono in particolare il trasporto marittimo di petrolio russo e limitano l\'accesso di alcune banche russe al sistema SWIFT. Gli analisti prevedono un aumento della volatilita nei mercati energetici europei nelle prossime settimane, con il gas naturale TTF che potrebbe tornare sopra i 35 EUR/MWh. L\'Italia, fortemente dipendente dalle importazioni energetiche, potrebbe risentirne in modo particolare.',
    source: 'Financial Times',
    url: '#',
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    category: 'Geopolitica',
    impact: 'high',
    imageUrl: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=800&h=450&fit=crop',
  },
  {
    id: '4',
    title: 'BCE: Lagarde apre a ulteriore allentamento monetario in aprile',
    description: 'La presidente della BCE Christine Lagarde ha dichiarato in un\'intervista che un ulteriore taglio dei tassi di interesse e sul tavolo per la prossima riunione di aprile. L\'inflazione nell\'eurozona e scesa al 2.1%, avvicinandosi all\'obiettivo del 2%, e i dati sulla crescita economica restano deboli, soprattutto in Germania e Francia. Un taglio di 25 punti base porterebbe il tasso di riferimento al 2.40%, il livello piu basso dal 2023. I mercati obbligazionari europei hanno gia scontato la mossa, con i rendimenti del Bund tedesco a 10 anni in calo al 2.15%.',
    source: 'Il Sole 24 Ore',
    url: '#',
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
    category: 'Banche Centrali',
    impact: 'high',
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=450&fit=crop',
  },
  {
    id: '5',
    title: 'Petrolio in calo: timori di rallentamento della domanda cinese',
    description: 'I prezzi del petrolio WTI sono scesi dell\'1.8% a $68.42 al barile dopo che i dati PMI manifatturiero cinese hanno deluso le aspettative, attestandosi a 48.3 punti contro i 50.1 previsti. E il terzo mese consecutivo in territorio di contrazione, alimentando i timori che la seconda economia mondiale stia rallentando piu del previsto. L\'OPEC+ si riunira la prossima settimana per discutere eventuali tagli alla produzione, ma le divisioni interne tra i membri rendono incerto l\'esito. Gli analisti di Goldman Sachs hanno rivisto al ribasso le previsioni per il Brent a fine anno, da $85 a $78 al barile.',
    source: 'CNBC',
    url: '#',
    publishedAt: new Date(Date.now() - 14400000).toISOString(),
    category: 'Mercati',
    impact: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&h=450&fit=crop',
  },
  {
    id: '6',
    title: 'Apple annuncia buyback da $110B, il piu grande della storia',
    description: 'Apple ha annunciato un programma di riacquisto di azioni proprie da $110 miliardi, il piu grande mai realizzato da una singola azienda. La mossa arriva dopo risultati trimestrali migliori delle attese, con ricavi in crescita del 5% a $95.4 miliardi. Il segmento servizi ha raggiunto un nuovo record a $24.2 miliardi, compensando la debolezza nelle vendite di iPhone in Cina. Il titolo e salito del 2.3% nell\'after-hours. Warren Buffett, il cui fondo Berkshire Hathaway detiene ancora una partecipazione significativa, ha commentato positivamente la strategia di allocazione del capitale di Tim Cook.',
    source: 'MarketWatch',
    url: '#',
    publishedAt: new Date(Date.now() - 18000000).toISOString(),
    category: 'Earnings',
    impact: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&h=450&fit=crop',
  },
  {
    id: '7',
    title: 'Oro ai massimi storici sopra $2,980: corsa ai beni rifugio',
    description: 'L\'oro ha toccato un nuovo massimo storico a $2,987 l\'oncia, avvicinandosi alla soglia psicologica dei $3,000. Il rally e alimentato da una combinazione di fattori: le tensioni geopolitiche in Medio Oriente, le aspettative di tagli dei tassi da parte delle principali banche centrali, e gli acquisti massicci da parte delle banche centrali di Cina e India. Gli ETF sull\'oro hanno registrato afflussi netti per $4.2 miliardi solo nell\'ultimo mese. Gli analisti di UBS prevedono che l\'oro possa raggiungere i $3,200 entro fine anno se il contesto macro resta favorevole.',
    source: 'Reuters',
    url: '#',
    publishedAt: new Date(Date.now() - 21600000).toISOString(),
    category: 'Mercati',
    impact: 'medium',
    imageUrl: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?w=800&h=450&fit=crop',
  },
  {
    id: '8',
    title: 'USA-Cina: nuovi dazi su semiconduttori, Pechino risponde',
    description: 'L\'amministrazione americana ha imposto nuovi dazi del 25% sulle importazioni di semiconduttori cinesi, estendendo le restrizioni anche ai chip legacy utilizzati nell\'automotive e nell\'elettronica di consumo. La Cina ha risposto immediatamente annunciando dazi del 15% su prodotti agricoli americani, tra cui soia, mais e carne suina, e ha avviato un\'indagine antidumping sulle importazioni di polipropilene dagli USA. Le azioni dei produttori di chip europei come ASML e Infineon sono scese del 3-4%, mentre i futures sui cereali a Chicago hanno registrato un\'impennata. Gli esperti temono un\'escalation che potrebbe rallentare la crescita globale.',
    source: 'ANSA',
    url: '#',
    publishedAt: new Date(Date.now() - 25200000).toISOString(),
    category: 'Geopolitica',
    impact: 'high',
    imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=450&fit=crop',
  },
];

export const mockCalendar: CalendarEvent[] = [
  {
    id: '1',
    date: '2026-03-18',
    time: '14:30',
    event: 'Riunione FOMC - Decisione Tassi FED',
    country: 'US',
    impact: 'high',
    forecast: '4.25%',
    previous: '4.50%',
  },
  {
    id: '2',
    date: '2026-03-19',
    time: '10:00',
    event: 'Indice ZEW Sentiment Economico - Germania',
    country: 'DE',
    impact: 'medium',
    forecast: '45.2',
    previous: '43.7',
  },
  {
    id: '3',
    date: '2026-03-20',
    time: '13:45',
    event: 'Riunione BCE - Decisione Tassi',
    country: 'EU',
    impact: 'high',
    forecast: '2.50%',
    previous: '2.65%',
  },
  {
    id: '4',
    date: '2026-03-21',
    time: '08:00',
    event: 'PIL UK Q4 (finale)',
    country: 'GB',
    impact: 'medium',
    forecast: '0.3%',
    previous: '0.1%',
  },
  {
    id: '5',
    date: '2026-03-24',
    time: '15:00',
    event: 'Vendite Case Esistenti USA',
    country: 'US',
    impact: 'low',
    forecast: '4.15M',
    previous: '4.08M',
  },
  {
    id: '6',
    date: '2026-03-25',
    time: '00:50',
    event: 'Riunione BoJ - Verbali',
    country: 'JP',
    impact: 'medium',
  },
  {
    id: '7',
    date: '2026-03-26',
    time: '14:30',
    event: 'PCE Core Price Index USA',
    country: 'US',
    impact: 'high',
    forecast: '2.6%',
    previous: '2.8%',
  },
  {
    id: '8',
    date: '2026-03-28',
    time: 'All Day',
    event: 'Scadenza Opzioni Trimestrali (Triple Witching)',
    country: 'US',
    impact: 'high',
  },
];
