import { MarketItem, NewsItem, CalendarEvent } from './types';

export const mockMarketData: MarketItem[] = [
  // Indici
  { symbol: 'SPX', name: 'S&P 500', price: 5667.56, change: 42.31, changePercent: 0.75, category: 'index' },
  { symbol: 'IXIC', name: 'NASDAQ', price: 17808.34, change: -23.45, changePercent: -0.13, category: 'index' },
  { symbol: 'FTSEMIB', name: 'FTSE MIB', price: 38245.12, change: 312.78, changePercent: 0.82, category: 'index' },
  { symbol: 'GDAXI', name: 'DAX', price: 22456.89, change: 156.34, changePercent: 0.70, category: 'index' },
  { symbol: 'N225', name: 'Nikkei 225', price: 38912.45, change: -187.23, changePercent: -0.48, category: 'index' },
  // Materie prime
  { symbol: 'GC=F', name: 'Oro', price: 2987.40, change: 18.50, changePercent: 0.62, category: 'commodity' },
  { symbol: 'CL=F', name: 'Petrolio WTI', price: 68.42, change: -1.23, changePercent: -1.77, category: 'commodity' },
  // Crypto
  { symbol: 'BTC', name: 'Bitcoin', price: 84235.67, change: 1245.89, changePercent: 1.50, category: 'crypto' },
  { symbol: 'ETH', name: 'Ethereum', price: 1925.34, change: -42.12, changePercent: -2.14, category: 'crypto' },
  // Valute
  { symbol: 'EURUSD', name: 'EUR/USD', price: 1.0892, change: 0.0023, changePercent: 0.21, category: 'currency' },
  { symbol: 'EURGBP', name: 'EUR/GBP', price: 0.8367, change: -0.0012, changePercent: -0.14, category: 'currency' },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'La FED mantiene i tassi invariati, segnala possibili tagli nel Q3',
    description: 'Il Federal Open Market Committee ha deciso di mantenere il tasso dei fondi federali al 4.25%-4.50%. Powell ha indicato che i tagli potrebbero iniziare nel terzo trimestre se l\'inflazione continua a scendere.',
    source: 'Reuters',
    url: '#',
    publishedAt: new Date().toISOString(),
    category: 'Banche Centrali',
    impact: 'high',
  },
  {
    id: '2',
    title: 'NVIDIA supera le stime: ricavi record a $39.3B nel Q4',
    description: 'NVIDIA ha riportato ricavi per $39.3 miliardi nel quarto trimestre, superando le stime degli analisti di $37.1B. La divisione data center ha trainato la crescita con un +78% anno su anno.',
    source: 'Bloomberg',
    url: '#',
    publishedAt: new Date(Date.now() - 3600000).toISOString(),
    category: 'Earnings',
    impact: 'high',
  },
  {
    id: '3',
    title: 'UE approva nuove sanzioni contro la Russia, impatto su energia europea',
    description: 'L\'Unione Europea ha approvato il quindicesimo pacchetto di sanzioni contro la Russia, colpendo il settore energetico e le esportazioni di GNL. Si prevede volatilità nei mercati energetici europei.',
    source: 'Financial Times',
    url: '#',
    publishedAt: new Date(Date.now() - 7200000).toISOString(),
    category: 'Geopolitica',
    impact: 'high',
  },
  {
    id: '4',
    title: 'BCE: Lagarde apre a ulteriore allentamento monetario in aprile',
    description: 'La presidente della BCE Christine Lagarde ha dichiarato che un ulteriore taglio dei tassi è possibile alla prossima riunione di aprile, citando il rallentamento dell\'inflazione nell\'eurozona.',
    source: 'Il Sole 24 Ore',
    url: '#',
    publishedAt: new Date(Date.now() - 10800000).toISOString(),
    category: 'Banche Centrali',
    impact: 'high',
  },
  {
    id: '5',
    title: 'Petrolio in calo: timori di rallentamento della domanda cinese',
    description: 'I prezzi del petrolio sono scesi dell\'1.8% dopo che i dati PMI manifatturiero cinese hanno deluso le aspettative, segnalando una contrazione per il terzo mese consecutivo.',
    source: 'CNBC',
    url: '#',
    publishedAt: new Date(Date.now() - 14400000).toISOString(),
    category: 'Mercati',
    impact: 'medium',
  },
  {
    id: '6',
    title: 'Apple annuncia buyback da $110B, il più grande della storia',
    description: 'Apple ha annunciato un programma di riacquisto di azioni proprie da $110 miliardi, il più grande nella storia aziendale. Il titolo sale del 2.3% nell\'after-hours.',
    source: 'MarketWatch',
    url: '#',
    publishedAt: new Date(Date.now() - 18000000).toISOString(),
    category: 'Earnings',
    impact: 'medium',
  },
  {
    id: '7',
    title: 'Oro ai massimi storici sopra $2,980: corsa ai beni rifugio',
    description: 'L\'oro ha toccato un nuovo massimo storico superando i $2,980 l\'oncia, spinto dalle tensioni geopolitiche in Medio Oriente e dalle aspettative di tagli dei tassi.',
    source: 'Reuters',
    url: '#',
    publishedAt: new Date(Date.now() - 21600000).toISOString(),
    category: 'Mercati',
    impact: 'medium',
  },
  {
    id: '8',
    title: 'USA-Cina: nuovi dazi su semiconduttori, Pechino risponde',
    description: 'Washington ha imposto nuovi dazi del 25% sulle importazioni di semiconduttori cinesi. La Cina ha annunciato misure di ritorsione su prodotti agricoli americani.',
    source: 'ANSA',
    url: '#',
    publishedAt: new Date(Date.now() - 25200000).toISOString(),
    category: 'Geopolitica',
    impact: 'high',
  },
];

export const mockCalendar: CalendarEvent[] = [
  {
    id: '1',
    date: '2026-03-18',
    time: '14:30',
    event: 'Riunione FOMC - Decisione Tassi FED',
    country: 'US',
    impact: 'high',
    forecast: '4.25%',
    previous: '4.50%',
  },
  {
    id: '2',
    date: '2026-03-19',
    time: '10:00',
    event: 'Indice ZEW Sentiment Economico - Germania',
    country: 'DE',
    impact: 'medium',
    forecast: '45.2',
    previous: '43.7',
  },
  {
    id: '3',
    date: '2026-03-20',
    time: '13:45',
    event: 'Riunione BCE - Decisione Tassi',
    country: 'EU',
    impact: 'high',
    forecast: '2.50%',
    previous: '2.65%',
  },
  {
    id: '4',
    date: '2026-03-21',
    time: '08:00',
    event: 'PIL UK Q4 (finale)',
    country: 'GB',
    impact: 'medium',
    forecast: '0.3%',
    previous: '0.1%',
  },
  {
    id: '5',
    date: '2026-03-24',
    time: '15:00',
    event: 'Vendite Case Esistenti USA',
    country: 'US',
    impact: 'low',
    forecast: '4.15M',
    previous: '4.08M',
  },
  {
    id: '6',
    date: '2026-03-25',
    time: '00:50',
    event: 'Riunione BoJ - Verbali',
    country: 'JP',
    impact: 'medium',
  },
  {
    id: '7',
    date: '2026-03-26',
    time: '14:30',
    event: 'PCE Core Price Index USA',
    country: 'US',
    impact: 'high',
    forecast: '2.6%',
    previous: '2.8%',
  },
  {
    id: '8',
    date: '2026-03-28',
    time: 'All Day',
    event: 'Scadenza Opzioni Trimestrali (Triple Witching)',
    country: 'US',
    impact: 'high',
  },
];
